package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chatlist generated by hbm2java
 */
public class Chatlist  implements java.io.Serializable {


     private Integer idchatlist;
     private Lecturer lecturer;
     private Student student;
     private Date lastmsgtime;
     private Integer msgcount;
     private String lastmsgtext;
     private String state;
     private Set<Chat> chats = new HashSet<Chat>(0);

    public Chatlist() {
    }

	
    public Chatlist(Lecturer lecturer, Student student) {
        this.lecturer = lecturer;
        this.student = student;
    }
    public Chatlist(Lecturer lecturer, Student student, Date lastmsgtime, Integer msgcount, String lastmsgtext, String state, Set<Chat> chats) {
       this.lecturer = lecturer;
       this.student = student;
       this.lastmsgtime = lastmsgtime;
       this.msgcount = msgcount;
       this.lastmsgtext = lastmsgtext;
       this.state = state;
       this.chats = chats;
    }
   
    public Integer getIdchatlist() {
        return this.idchatlist;
    }
    
    public void setIdchatlist(Integer idchatlist) {
        this.idchatlist = idchatlist;
    }
    public Lecturer getLecturer() {
        return this.lecturer;
    }
    
    public void setLecturer(Lecturer lecturer) {
        this.lecturer = lecturer;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Date getLastmsgtime() {
        return this.lastmsgtime;
    }
    
    public void setLastmsgtime(Date lastmsgtime) {
        this.lastmsgtime = lastmsgtime;
    }
    public Integer getMsgcount() {
        return this.msgcount;
    }
    
    public void setMsgcount(Integer msgcount) {
        this.msgcount = msgcount;
    }
    public String getLastmsgtext() {
        return this.lastmsgtext;
    }
    
    public void setLastmsgtext(String lastmsgtext) {
        this.lastmsgtext = lastmsgtext;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set<Chat> getChats() {
        return this.chats;
    }
    
    public void setChats(Set<Chat> chats) {
        this.chats = chats;
    }




}


