package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private Integer idchat;
     private Chatlist chatlist;
     private String msg;
     private Date msgtime;
     private String state;

    public Chat() {
    }

	
    public Chat(Chatlist chatlist) {
        this.chatlist = chatlist;
    }
    public Chat(Chatlist chatlist, String msg, Date msgtime, String state) {
       this.chatlist = chatlist;
       this.msg = msg;
       this.msgtime = msgtime;
       this.state = state;
    }
   
    public Integer getIdchat() {
        return this.idchat;
    }
    
    public void setIdchat(Integer idchat) {
        this.idchat = idchat;
    }
    public Chatlist getChatlist() {
        return this.chatlist;
    }
    
    public void setChatlist(Chatlist chatlist) {
        this.chatlist = chatlist;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public Date getMsgtime() {
        return this.msgtime;
    }
    
    public void setMsgtime(Date msgtime) {
        this.msgtime = msgtime;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


