package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Examvivashedule generated by hbm2java
 */
public class Examvivashedule  implements java.io.Serializable {


     private int idexamvivashedule;
     private Lecturehall lecturehall;
     private Subjectvisebatch subjectvisebatch;
     private Date date;
     private Date starttime;
     private Date endtime;
     private String location;
     private String state;
     private String type;

    public Examvivashedule() {
    }

	
    public Examvivashedule(int idexamvivashedule, Lecturehall lecturehall, Subjectvisebatch subjectvisebatch) {
        this.idexamvivashedule = idexamvivashedule;
        this.lecturehall = lecturehall;
        this.subjectvisebatch = subjectvisebatch;
    }
    public Examvivashedule(int idexamvivashedule, Lecturehall lecturehall, Subjectvisebatch subjectvisebatch, Date date, Date starttime, Date endtime, String location, String state, String type) {
       this.idexamvivashedule = idexamvivashedule;
       this.lecturehall = lecturehall;
       this.subjectvisebatch = subjectvisebatch;
       this.date = date;
       this.starttime = starttime;
       this.endtime = endtime;
       this.location = location;
       this.state = state;
       this.type = type;
    }
   
    public int getIdexamvivashedule() {
        return this.idexamvivashedule;
    }
    
    public void setIdexamvivashedule(int idexamvivashedule) {
        this.idexamvivashedule = idexamvivashedule;
    }
    public Lecturehall getLecturehall() {
        return this.lecturehall;
    }
    
    public void setLecturehall(Lecturehall lecturehall) {
        this.lecturehall = lecturehall;
    }
    public Subjectvisebatch getSubjectvisebatch() {
        return this.subjectvisebatch;
    }
    
    public void setSubjectvisebatch(Subjectvisebatch subjectvisebatch) {
        this.subjectvisebatch = subjectvisebatch;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


