package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Lecturehall generated by hbm2java
 */
public class Lecturehall  implements java.io.Serializable {


     private Integer idlecturehall;
     private String lecturehallnumber;
     private Set<Examvivashedule> examvivashedules = new HashSet<Examvivashedule>(0);
     private Set<Normalclassshedule> normalclassshedules = new HashSet<Normalclassshedule>(0);

    public Lecturehall() {
    }

    public Lecturehall(String lecturehallnumber, Set<Examvivashedule> examvivashedules, Set<Normalclassshedule> normalclassshedules) {
       this.lecturehallnumber = lecturehallnumber;
       this.examvivashedules = examvivashedules;
       this.normalclassshedules = normalclassshedules;
    }
   
    public Integer getIdlecturehall() {
        return this.idlecturehall;
    }
    
    public void setIdlecturehall(Integer idlecturehall) {
        this.idlecturehall = idlecturehall;
    }
    public String getLecturehallnumber() {
        return this.lecturehallnumber;
    }
    
    public void setLecturehallnumber(String lecturehallnumber) {
        this.lecturehallnumber = lecturehallnumber;
    }
    public Set<Examvivashedule> getExamvivashedules() {
        return this.examvivashedules;
    }
    
    public void setExamvivashedules(Set<Examvivashedule> examvivashedules) {
        this.examvivashedules = examvivashedules;
    }
    public Set<Normalclassshedule> getNormalclassshedules() {
        return this.normalclassshedules;
    }
    
    public void setNormalclassshedules(Set<Normalclassshedule> normalclassshedules) {
        this.normalclassshedules = normalclassshedules;
    }




}


