package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Lecturer generated by hbm2java
 */
public class Lecturer  implements java.io.Serializable {


     private Integer idlecturer;
     private String fname;
     private String lname;
     private String nic;
     private String email;
     private String mobile;
     private String telephone;
     private String state;
     private Set<Subjectvisebatch> subjectvisebatches = new HashSet<Subjectvisebatch>(0);
     private Set<Chatlist> chatlists = new HashSet<Chatlist>(0);

    public Lecturer() {
    }

    public Lecturer(String fname, String lname, String nic, String email, String mobile, String telephone, String state, Set<Subjectvisebatch> subjectvisebatches, Set<Chatlist> chatlists) {
       this.fname = fname;
       this.lname = lname;
       this.nic = nic;
       this.email = email;
       this.mobile = mobile;
       this.telephone = telephone;
       this.state = state;
       this.subjectvisebatches = subjectvisebatches;
       this.chatlists = chatlists;
    }
   
    public Integer getIdlecturer() {
        return this.idlecturer;
    }
    
    public void setIdlecturer(Integer idlecturer) {
        this.idlecturer = idlecturer;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set<Subjectvisebatch> getSubjectvisebatches() {
        return this.subjectvisebatches;
    }
    
    public void setSubjectvisebatches(Set<Subjectvisebatch> subjectvisebatches) {
        this.subjectvisebatches = subjectvisebatches;
    }
    public Set<Chatlist> getChatlists() {
        return this.chatlists;
    }
    
    public void setChatlists(Set<Chatlist> chatlists) {
        this.chatlists = chatlists;
    }




}


