package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idlogin;
     private String username;
     private String password;

    public Login() {
    }

    public Login(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdlogin() {
        return this.idlogin;
    }
    
    public void setIdlogin(Integer idlogin) {
        this.idlogin = idlogin;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


