package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Normalclassshedule generated by hbm2java
 */
public class Normalclassshedule  implements java.io.Serializable {


     private Integer idnormalclassshedule;
     private Lecturehall lecturehall;
     private Subjectvisebatch subjectvisebatch;
     private Date date;
     private Date starttime;
     private Date endtime;
     private String location;
     private String state;

    public Normalclassshedule() {
    }

	
    public Normalclassshedule(Lecturehall lecturehall, Subjectvisebatch subjectvisebatch) {
        this.lecturehall = lecturehall;
        this.subjectvisebatch = subjectvisebatch;
    }
    public Normalclassshedule(Lecturehall lecturehall, Subjectvisebatch subjectvisebatch, Date date, Date starttime, Date endtime, String location, String state) {
       this.lecturehall = lecturehall;
       this.subjectvisebatch = subjectvisebatch;
       this.date = date;
       this.starttime = starttime;
       this.endtime = endtime;
       this.location = location;
       this.state = state;
    }
   
    public Integer getIdnormalclassshedule() {
        return this.idnormalclassshedule;
    }
    
    public void setIdnormalclassshedule(Integer idnormalclassshedule) {
        this.idnormalclassshedule = idnormalclassshedule;
    }
    public Lecturehall getLecturehall() {
        return this.lecturehall;
    }
    
    public void setLecturehall(Lecturehall lecturehall) {
        this.lecturehall = lecturehall;
    }
    public Subjectvisebatch getSubjectvisebatch() {
        return this.subjectvisebatch;
    }
    
    public void setSubjectvisebatch(Subjectvisebatch subjectvisebatch) {
        this.subjectvisebatch = subjectvisebatch;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


