package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0



/**
 * Notificationlist generated by hbm2java
 */
public class Notificationlist  implements java.io.Serializable {


     private Integer idnotificationlist;
     private Student student;
     private String topic;
     private String details;
     private String state;

    public Notificationlist() {
    }

	
    public Notificationlist(Student student) {
        this.student = student;
    }
    public Notificationlist(Student student, String topic, String details, String state) {
       this.student = student;
       this.topic = topic;
       this.details = details;
       this.state = state;
    }
   
    public Integer getIdnotificationlist() {
        return this.idnotificationlist;
    }
    
    public void setIdnotificationlist(Integer idnotificationlist) {
        this.idnotificationlist = idnotificationlist;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


