package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Specialnotifications generated by hbm2java
 */
public class Specialnotifications  implements java.io.Serializable {


     private Integer idspecialnotifications;
     private Student student;
     private String header;
     private String description;
     private Date date;
     private String state;

    public Specialnotifications() {
    }

	
    public Specialnotifications(Student student) {
        this.student = student;
    }
    public Specialnotifications(Student student, String header, String description, Date date, String state) {
       this.student = student;
       this.header = header;
       this.description = description;
       this.date = date;
       this.state = state;
    }
   
    public Integer getIdspecialnotifications() {
        return this.idspecialnotifications;
    }
    
    public void setIdspecialnotifications(Integer idspecialnotifications) {
        this.idspecialnotifications = idspecialnotifications;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getHeader() {
        return this.header;
    }
    
    public void setHeader(String header) {
        this.header = header;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


