package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0



/**
 * StudentHasSubjectvisebatch generated by hbm2java
 */
public class StudentHasSubjectvisebatch  implements java.io.Serializable {


     private Integer studentHasSubjectvisebatchid;
     private Subjectvisebatch subjectvisebatch;
     private Student student;

    public StudentHasSubjectvisebatch() {
    }

    public StudentHasSubjectvisebatch(Subjectvisebatch subjectvisebatch, Student student) {
       this.subjectvisebatch = subjectvisebatch;
       this.student = student;
    }
   
    public Integer getStudentHasSubjectvisebatchid() {
        return this.studentHasSubjectvisebatchid;
    }
    
    public void setStudentHasSubjectvisebatchid(Integer studentHasSubjectvisebatchid) {
        this.studentHasSubjectvisebatchid = studentHasSubjectvisebatchid;
    }
    public Subjectvisebatch getSubjectvisebatch() {
        return this.subjectvisebatch;
    }
    
    public void setSubjectvisebatch(Subjectvisebatch subjectvisebatch) {
        this.subjectvisebatch = subjectvisebatch;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


