package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0



/**
 * Studentlogin generated by hbm2java
 */
public class Studentlogin  implements java.io.Serializable {


     private Integer idstudentlogin;
     private Student student;
     private String nic;
     private String password;

    public Studentlogin() {
    }

	
    public Studentlogin(Student student) {
        this.student = student;
    }
    public Studentlogin(Student student, String nic, String password) {
       this.student = student;
       this.nic = nic;
       this.password = password;
    }
   
    public Integer getIdstudentlogin() {
        return this.idstudentlogin;
    }
    
    public void setIdstudentlogin(Integer idstudentlogin) {
        this.idstudentlogin = idstudentlogin;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


