package pojos;
// Generated Nov 13, 2017 1:11:38 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subjectvisebatch generated by hbm2java
 */
public class Subjectvisebatch  implements java.io.Serializable {


     private Integer idsubjectvisebatch;
     private Lecturer lecturer;
     private Subject subject;
     private String subjectvisebatchcode;
     private Set<Examvivashedule> examvivashedules = new HashSet<Examvivashedule>(0);
     private Set<Normalclassshedule> normalclassshedules = new HashSet<Normalclassshedule>(0);
     private Set<StudentHasSubjectvisebatch> studentHasSubjectvisebatches = new HashSet<StudentHasSubjectvisebatch>(0);

    public Subjectvisebatch() {
    }

	
    public Subjectvisebatch(Lecturer lecturer, Subject subject) {
        this.lecturer = lecturer;
        this.subject = subject;
    }
    public Subjectvisebatch(Lecturer lecturer, Subject subject, String subjectvisebatchcode, Set<Examvivashedule> examvivashedules, Set<Normalclassshedule> normalclassshedules, Set<StudentHasSubjectvisebatch> studentHasSubjectvisebatches) {
       this.lecturer = lecturer;
       this.subject = subject;
       this.subjectvisebatchcode = subjectvisebatchcode;
       this.examvivashedules = examvivashedules;
       this.normalclassshedules = normalclassshedules;
       this.studentHasSubjectvisebatches = studentHasSubjectvisebatches;
    }
   
    public Integer getIdsubjectvisebatch() {
        return this.idsubjectvisebatch;
    }
    
    public void setIdsubjectvisebatch(Integer idsubjectvisebatch) {
        this.idsubjectvisebatch = idsubjectvisebatch;
    }
    public Lecturer getLecturer() {
        return this.lecturer;
    }
    
    public void setLecturer(Lecturer lecturer) {
        this.lecturer = lecturer;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public String getSubjectvisebatchcode() {
        return this.subjectvisebatchcode;
    }
    
    public void setSubjectvisebatchcode(String subjectvisebatchcode) {
        this.subjectvisebatchcode = subjectvisebatchcode;
    }
    public Set<Examvivashedule> getExamvivashedules() {
        return this.examvivashedules;
    }
    
    public void setExamvivashedules(Set<Examvivashedule> examvivashedules) {
        this.examvivashedules = examvivashedules;
    }
    public Set<Normalclassshedule> getNormalclassshedules() {
        return this.normalclassshedules;
    }
    
    public void setNormalclassshedules(Set<Normalclassshedule> normalclassshedules) {
        this.normalclassshedules = normalclassshedules;
    }
    public Set<StudentHasSubjectvisebatch> getStudentHasSubjectvisebatches() {
        return this.studentHasSubjectvisebatches;
    }
    
    public void setStudentHasSubjectvisebatches(Set<StudentHasSubjectvisebatch> studentHasSubjectvisebatches) {
        this.studentHasSubjectvisebatches = studentHasSubjectvisebatches;
    }




}


